### ISSUE TITLE
Environment is not able to be overridden.

### ISSUE THREAD

**Issue by blkdot** [castleadmin/nx-plugins#9]
I can see these env vars in this sdk.
{
  "AWS_LAMBDA_FUNCTION_VERSION": "$LATEST",
  "AWS_EXECUTION_ENV": "AWS_Lambda_nodejs20.x",
  "HOSTNAME": 
  "POWERTOOLS_SERVICE_NAME": "lambda",
  "AWS_DEFAULT_REGION": "eu-west-1",
  "AWS_LAMBDA_LOG_STREAM_NAME": "$LATEST",
  "AWS_REGION": "eu-west-1",
  "PWD": "/var/task",
  "_HANDLER": "index.exampleHandler",
  "TZ": ":/etc/localtime",
  "AWS_LAMBDA_FUNCTION_HANDLER": "index.exampleHandler",
  "LAMBDA_TASK_ROOT": "/var/task",
  "HOME": "/root",
  "AWS_SAM_LOCAL": "true",
  "LANG": "en_US.UTF-8",
  "AWS_SECRET_ACCESS_KEY":
  "AWS_LAMBDA_LOG_GROUP_NAME": 
  "AWS_LAMBDA_RUNTIME_API": "127.0.0.1:9001",
  "AWS_LAMBDA_FUNCTION_MEMORY_SIZE": "128",
  "LAMBDA_RUNTIME_DIR": "/var/runtime",
  "AWS_LAMBDA_LOG_FORMAT": "JSON",
  "AWS_LAMBDA_LOG_LEVEL": "INFO",
  "ENVIRONMENT": "Dev1",
  "AWS_LAMBDA_FUNCTION_TIMEOUT": "29",
  "AWS_ACCOUNT_ID": "123456789012",
  "SHLVL": "0",
  "AWS_ACCESS_KEY_ID": 
  "LD_LIBRARY_PATH": "/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib",
  "NODE_PATH": "/opt/nodejs/node20/node_modules:/opt/nodejs/node_modules:/var/runtime/node_modules:/var/runtime:/var/task",
  "AWS_LAMBDA_FUNCTION_NAME": "ExampleFunctionB28997EC",
  "PATH": "/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin",
  "AWS_SESSION_TOKEN": ""
}

But I can not override some env vars by setting them in env file such as "TZ", "SHLVL"

**Comment by castleadmin** [comment]
Hi @blkdot, I also wasn't able to override the SHLVL environment variable with the help of the `.env` file. However, I was able to overwrite EDITOR which is set on my Laptop. Therefore, I assume that the overridden variables are overridden again during the execution.

You could try to set the TZ variable via a shell initialization file like `.bashrc`.

**Comment by blkdot** [comment]
Got it. thanks
